export const PASCAL_VOC_LABELS = [
  'background',
  'aeroplane',
  'bicycle',
  'bird',
  'boat',
  'bottle',
  'bus',
  'car',
  'cat',
  'chair',
  'cow',
  'diningtable',
  'dog',
  'horse',
  'motorbike',
  'person',
  'pottedplant',
  'sheep',
  'sofa',
  'train',
  'tvmonitor',
] as const;

export type PascalVocLabel = (typeof PASCAL_VOC_LABELS)[number];
